### ISSUE TITLE
Charte Graphique Général

### ISSUE THREAD

**Issue by gabriel-ledina** [Aeris-py/Decadrer#2]
1. Fond du site blanc
2. Police général : Noir
3. Police :  Avant Garde Gothic -> # Voir la police et l'ajouter.
4. Image de fond ->#En attente.

---

Structure à respecter.

1. Faire un schéma.
---

**OBJECTIFS GRAPHIQUE**
_Obtenir un résultat Moderne simple et épuré avec l’utilisation de la Police_
 : Avant-Garde Gothic. 

Gardez les couleurs de base Noir et Blanc pour rester dans un style plus Moderne.
La couleur des liens Hypertexte comme vous l’avez demander d’un point du vue visibilité ne peux pas être accepté la couleur Orange est moins visible avec le fond blanc.
Les images de fond peuvent effectivement être placées comme demandé.

```html
<link href="fonts/roboto/stylesheet.css" rel="stylesheet" type = "text/css" />) ou CSS (en écrivant @import url("fonts/roboto/stylesheet.css ")).
```
---

**Comment by gabriel-ledina** [comment]
### Police non fonctionnel, à fix.

**Comment by JulienVvert** [comment]
Police fix

**Comment by gabriel-ledina** [comment]
La police est fix.
