### ISSUE TITLE
Page contact

### ISSUE THREAD

**Issue by JulienVvert** [Aeris-py/Decadrer#5]
Informations pour joindre/réclamations => Formulaire

**Comment by JulienVvert** [comment]
Formulaire en majorité fait : Prénom, nom, email, message

**Comment by JulienVvert** [comment]
A fix : Tout aligner

**Comment by JulienVvert** [comment]
A fix : zoom

**Comment by JulienVvert** [comment]
Zoom fix

**Comment by gabriel-ledina** [comment]
Le formulaire n'est pas responsiv

**Comment by JulienVvert** [comment]
Footer responsiv
